//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ngrams.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ngrams.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аркадий СТРУГАЦКИЙ, Борис СТРУГАЦКИЙ
        ///
        ///
        ///
        ///УЛИТКА НА СКЛОНЕ – 1 (БЕСПОКОЙСТВО)
        ///
        ///
        ///
        ///ГЛАВА ПЕРВАЯ
        ///
        ///С этой высоты лес был как пышная пятнистая пена, как огромная, на весь мир, рыхлая губка, как животное, которое затаилось когда-то в ожидании, а потом заснуло и поросло грубым мхом. Как бесформенная маска, скрывающая лицо, которое никто еще никогда не видел.
        ///
        ///Леонид Андреевич сбросил шлепанцы и сел, свесив босые ноги в пропасть. Ему показалось, что пятки сразу стали влажными, словно он и в самом деле пог [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string bespokoystvo {
            get {
                return ResourceManager.GetString("bespokoystvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аркадий Стругацкий, Борис Стругацкий
        ///
        ///Улитка на склоне
        ///
        ///		За поворотом, в глубине
        ///		Лесного лога
        ///		Готово будущее мне
        ///		Верней залога.
        ///
        ///		Его уже не втянешь в спор
        ///		И не заластишь,
        ///		Оно распахнуто, как бор,
        ///		Всё вглубь, всё настежь.
        ///
        ///    Б. Пастернак
        ///
        ///
        ///Тихо, тихо ползи,
        ///
        ///Улитка, по склону Фудзи,
        ///
        ///Вверх, до самых высот!
        ///
        ///    Исса, сын крестьянина
        ///
        ///
        ///
        ///Глава первая
        ///
        ///Перец
        ///
        ///С этой высоты лес был как пышная пятнистая пена; как огромная, на весь мир, рыхлая губка; как животное, ко [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ulitka_na_sklone {
            get {
                return ResourceManager.GetString("ulitka_na_sklone", resourceCulture);
            }
        }
    }
}
